# Generated by Django 4.0.4 on 2022-06-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_songs_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddSong',
        ),
    ]
