# Generated by Django 4.0.5 on 2022-06-29 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0002_remove_album_is_favorite_album_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='fav_s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='song',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.ManyToManyField(blank=True, related_name='fav_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
