# Generated by Django 4.0.4 on 2022-06-06 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_delete_addsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(blank=True, upload_to='uploads/songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='mp3', message='только mp3 формат')]),
        ),
    ]
