# Generated by Django 4.0.4 on 2022-06-07 18:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0004_alter_songs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(blank=True, upload_to='uploads/songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'], message='только mp3 формат')]),
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_list', models.TextField(blank=True, max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
