# Generated by Django 4.0.4 on 2022-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_songs_song_userlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='songs_link',
            field=models.TextField(blank=True, max_length=115, verbose_name='songs_link'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='play_list',
            field=models.CharField(max_length=115, verbose_name='play list'),
        ),
    ]
