# Generated by Django 4.0.4 on 2022-06-09 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0008_alter_songs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='songs_link',
            field=models.CharField(blank=True, max_length=115, verbose_name='songs_link'),
        ),
    ]
