# Generated by Django 4.0.4 on 2022-06-11 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_alter_songs_user_alter_userlist_songs_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song',
            field=models.FileField(blank=True, unique=True, upload_to='uploads/songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'], message='только mp3 формат')]),
        ),
    ]
